### ISSUE TITLE
couldn't create DomainParticipant on Win32.

### ISSUE THREAD

**Issue by lygstate** [oci-labs/node-opendds#13]
19796|28512) ERROR: InfoRepoDiscovery::get_dcps_info: unable to narrow DCPSInfo (file://repo.ior) for key DEFAULT_REPO.
(19796|28512) ERROR: DomainParticipantImpl::enable, add_domain_participant returned invalid id.
(19796|28512) ERROR: DomainParticipantFactoryImpl::create_participant, unable to enable DomainParticipant.
E:\CI-Cor-Ready\615\gmss-bs\my-dds\test.js:14
let participant = factory.create_participant(DOMAIN_ID, qos)
                          ^

Error: couldn't create DomainParticipant
    at Object.<anonymous> (E:\CI-Cor-Ready\615\gmss-bs\my-dds\test.js:14:27)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)

**Comment by iguessthislldo** [comment]
- Could you give more context on how you're trying to use Node-OpenDDS?
- Was the Info Repo running when this happened?
- Was the Node JS participant in the same folder as the Info Repo?
  - All the participants need to be able to read the same repo.ior file.

**Comment by mitza-oci** [comment]
The error `InfoRepoDiscovery::get_dcps_info:` is just a general OpenDDS usage issue, not specific to Node.js.  Please see the OpenDDS Developer's Guide (link is on http://opendds.org/documents).
